### ISSUE TITLE
Gmail password visible in plane text to everyone

### ISSUE THREAD

**Issue by iamkunal9** [parthivithakorecode/Bulk-Email-Sender#1]
Your gmail password are openly visible kindly change them try not to push a repo having password openly visible use github secrets

**Comment by iamkunal9** [comment]
https://github.com/parthivithakorecode/Bulk-Email-Sender/blob/main/php/send.php
Line 26 
🤞

**Comment by parthivithakorecode** [comment]
> Your gmail password are openly visible kindly change them try not to push a repo having password openly visible use github secrets


When you will open it in Local Host, you won't be able to get access to the php file, still for your reference, we have removed it.

**Comment by iamkunal9** [comment]
> > Your gmail password are openly visible kindly change them try not to push a repo having password openly visible use github secrets
> 
> When you will open it in Local Host, you won't be able to get access to the php file, still for your reference, we have removed it.
Pushing a repo having password (in your case its your google account password) in plane text is a bad idea!!!!
I know that the password written in php is not visible to client as it is a server side language but i didn't open the issue regarding that!!!
anyone doing dorking can head up to your repo and get your password and can access your account. Its a sever bug dude.
Do some research before closing any issue marking invalid

**Comment by iamkunal9** [comment]
And for your information updating the repo doesn't remove the password from the history.
Have a good DAY
